### ISSUE TITLE
Can I use your benchmark result as course staff reference materials?

### ISSUE THREAD

**Issue by xiezhq-hermann** [lbrito1/cstuff#1]
Thanks for your great job in analysing the AVL and Red-Black trees, I want to use them in a data structure course as reference notes. What should I do for getting your permission?

**Comment by lbrito1** [comment]
Hi Zhiqiang! Glad to hear you enjoyed my work. Sure, feel free to reference whatever you want. Just reference this repository and original posts (in https://codedeposit.wordpress.com/) when needed.

**Comment by xiezhq-hermann** [comment]
Thanks for your kindness, it's very helpful.
