### ISSUE TITLE
Benchmarking Red-Black tree and AVL tree 'delete' operation

### ISSUE THREAD

**Issue by NiekBeijloos** [lbrito1/cstuff#2]
Hi Ibrito,

I didn't find another way to approach you, so that's why I'm sending you a message in this form. I read your benchmark about Red-Black trees vs AVL trees: https://codedeposit.wordpress.com/2015/10/07/red-black-vs-avl/ and I think it is great! This is proof of what is the actual time complexity of the tree operations: 'Insert' and 'Search'. However,  I'm missing the benchmark of the 'Delete' operation. Do you see any chance of doing that in the future or have you already done that? 

I'm hoping to hear from you soon.

Thanks.
Niek

**Comment by lbrito1** [comment]
Hi Niek, great to hear from you! I'm glad you enjoyed that post. Its neat to see something from nearly a decade ago just randomly resurface. 

I have no plans of continuing to work on that project. It was mostly something I was doing after my masters to help practice CS basics with a lower-level language. I don't remember if I even implemented Delete (if not, here's probably why: https://softwareengineering.stackexchange.com/questions/301015/why-is-deletion-usually-much-harder-to-implement-than-insertion-in-many-data-str). This is still an open source repo though, feel free to contribute if you'd like.

Also I've moved from that blog address to a new one here, in case you're interested in reading more stuff (none of it C-related, I'm afraid!): https://lbrito.ca/blog/ . 

Cheers,
Leo
